#!/usr/bin/env bash
set -euo pipefail

BRANCH="scaffold/maven-java17-keycloak-kafka"

# sanity checks
if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  echo "ERROR: run this from the repository root (where .git lives)." >&2
  exit 1
fi

if ! git remote get-url origin > /dev/null 2>&1; then
  echo "ERROR: no 'origin' remote found. Add origin and re-run." >&2
  git remote -v || true
  exit 1
fi

echo "Fetching origin..."
git fetch origin --prune

# create or reset branch
if git ls-remote --heads origin "$BRANCH" | grep -q "$BRANCH"; then
  echo "Checking out branch from remote: $BRANCH"
  git checkout -B "$BRANCH" "origin/$BRANCH"
else
  if git show-ref --verify --quiet "refs/remotes/origin/main"; then
    echo "Creating branch $BRANCH from origin/main"
    git checkout -b "$BRANCH" origin/main
  else
    echo "Creating branch $BRANCH from current HEAD"
    git checkout -b "$BRANCH"
  fi
fi

echo "Creating directories..."
mkdir -p infra/keycloak infra/terraform
mkdir -p services/account-service/src/main/java/com/nbwealths/accountservice
mkdir -p services/account-service/src/main/java/com/nbwealths/accountservice/controller
mkdir -p services/account-service/src/main/java/com/nbwealths/accountservice/dto
mkdir -p services/account-service/src/main/java/com/nbwealths/accountservice/entity
mkdir -p services/account-service/src/main/java/com/nbwealths/accountservice/repository
mkdir -p services/account-service/src/main/java/com/nbwealths/accountservice/service
mkdir -p services/account-service/src/main/resources
mkdir -p services/account-service/src/main/resources/db/migration
mkdir -p services/account-service/src/test/java/com/nbwealths/accountservice

mkdir -p services/portfolio-service/src/main/java/com/nbwealths/portfoliosvc
mkdir -p services/portfolio-service/src/main/java/com/nbwealths/portfoliosvc/controller
mkdir -p services/portfolio-service/src/main/resources
mkdir -p services/portfolio-service/src/main/resources/db/migration

mkdir -p services/admin-service/src/main/java/com/nbwealths/adminsvc
mkdir -p services/admin-service/src/main/java/com/nbwealths/adminsvc/controller
mkdir -p services/admin-service/src/main/resources
mkdir -p services/admin-service/src/main/resources/db/migration

mkdir -p frontend/angular-app
mkdir -p .github/workflows

echo "Writing files..."

cat > pom.xml <<'EOF'
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.nbwealths</groupId>
    <artifactId>nbwealths-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>services/account-service</module>
        <module>services/portfolio-service</module>
        <module>services/admin-service</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <spring.boot.version>3.1.6</spring.boot.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.8.1</version>
                    <configuration>
                        <source>${maven.compiler.source}</source>
                        <target>${maven.compiler.target}</target>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
EOF

cat > README.md <<'EOF'
# nbwealths

Wealth management app monorepo — scaffold for learning and interview preparation.

This repository is generated by GitHub Copilot assistant. It contains three Spring Boot services (Account, Portfolio, Admin), an Angular frontend scaffold, local dev docker-compose (Postgres ×3, Kafka, Zookeeper, Keycloak), Terraform placeholders, and a GitHub Actions CI template.

Next steps:
- Branch scaffold/maven-java17-keycloak-kafka will contain the initial scaffold files.
- Run local dev with docker-compose (see infra/docker-compose.yml in the scaffold branch).

See the scaffold branch for the project layout and files.
EOF

cat > .env.example <<'EOF'
# environment variables (example)

# Database passwords (local only)
POSTGRES_ACCOUNT_DB=accountdb
POSTGRES_ACCOUNT_USER=account
POSTGRES_ACCOUNT_PASSWORD=accountpass

POSTGRES_PORTFOLIO_DB=portfoliodb
POSTGRES_PORTFOLIO_USER=portfolio
POSTGRES_PORTFOLIO_PASSWORD=portfoliopass

POSTGRES_ADMIN_DB=admindb
POSTGRES_ADMIN_USER=admin
POSTGRES_ADMIN_PASSWORD=adminpass

# Kafka
KAFKA_BOOTSTRAP_SERVERS=localhost:9092

# Keycloak (local)
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=admin
KEYCLOAK_URL=http://localhost:8080
KEYCLOAK_REALM=nb-wealths
KEYCLOAK_FRONTEND_CLIENT_ID=angular-frontend
KEYCLOAK_ACCOUNT_CLIENT_ID=account-service
KEYCLOAK_PORTFOLIO_CLIENT_ID=portfolio-service
KEYCLOAK_ADMIN_CLIENT_ID=admin-service

# Spring profile for local run
SPRING_PROFILES_ACTIVE=local

# Optional GHCR/CI creds (only if you plan to push images)
GHCR_REGISTRY=ghcr.io
GHCR_USERNAME=<your-gh-username>
GHCR_TOKEN=<ghcr-token>
EOF

cat > .gitignore <<'EOF'
.idea/
*.iml
target/
*.log
.env
**/target/
*.jar
.DS_Store
node_modules/
/frontend/angular-app/dist
EOF

cat > infra/docker-compose.yml <<'EOF'
version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  postgres-account:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_ACCOUNT_DB}
      POSTGRES_USER: ${POSTGRES_ACCOUNT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ACCOUNT_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata_account:/var/lib/postgresql/data

  postgres-portfolio:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_PORTFOLIO_DB}
      POSTGRES_USER: ${POSTGRES_PORTFOLIO_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PORTFOLIO_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata_portfolio:/var/lib/postgresql/data

  postgres-admin:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_ADMIN_DB}
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - pgdata_admin:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./infra/keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro
    environment:
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm.json

  account-service:
    build: ./services/account-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres-account
      - kafka
      - keycloak
    ports:
      - "8081:8081"

  portfolio-service:
    build: ./services/portfolio-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres-portfolio
      - kafka
      - keycloak
    ports:
      - "8082:8082"

  admin-service:
    build: ./services/admin-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres-admin
      - kafka
      - keycloak
    ports:
      - "8083:8083"

volumes:
  pgdata_account:
  pgdata_portfolio:
  pgdata_admin:
EOF

cat > infra/keycloak/realm.json <<'EOF'
{
  "realm": "nb-wealths",
  "enabled": true,
  "clients": [
    {
      "clientId": "angular-frontend",
      "publicClient": true,
      "redirectUris": ["http://localhost:4200/*"]
    },
    {
      "clientId": "account-service",
      "publicClient": false,
      "secret": "account-secret"
    },
    {
      "clientId": "portfolio-service",
      "publicClient": false,
      "secret": "portfolio-secret"
    },
    {
      "clientId": "admin-service",
      "publicClient": false,
      "secret": "admin-secret"
    }
  ],
  "roles": {
    "realm": ["ROLE_USER", "ROLE_ADMIN"]
  },
  "users": [
    {
      "username": "alice",
      "enabled": true,
      "emailVerified": true,
      "credentials": [ { "type": "password", "value": "password" } ],
      "realmRoles": ["ROLE_USER"]
    },
    {
      "username": "bob",
      "enabled": true,
      "emailVerified": true,
      "credentials": [ { "type": "password", "value": "adminpass" } ],
      "realmRoles": ["ROLE_ADMIN"]
    }
  ]
}
EOF

cat > infra/terraform/README.md <<'EOF'
# Terraform placeholders

This directory will contain Terraform modules to provision GCP resources (Cloud Run, Cloud SQL, Pub/Sub) and AWS resources (S3, SES).
EOF

cat > .github/workflows/ci.yml <<'EOF'
name: CI

on:
  push:
    branches:
      - main
      - scaffold/maven-java17-keycloak-kafka

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        run: mvn -T 1C -DskipTests=false package --file pom.xml

      - name: Run tests
        run: mvn test -T 1C

      - name: Build Docker images (placeholder)
        run: echo "Build Docker images and push to GHCR (configure secrets.GHCR_TOKEN)"
EOF

# service: account-service
cat > services/account-service/pom.xml <<'EOF'
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.nbwealths</groupId>
        <artifactId>nbwealths-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>account-service</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>postgresql</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>kafka</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
EOF

cat > services/account-service/src/main/java/com/nbwealths/accountservice/AccountServiceApplication.java <<'EOF'
package com.nbwealths.accountservice;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class AccountServiceApplication {
    public static void main(String[] args) {
        SpringApplication.run(AccountServiceApplication.class, args);
    }
}
EOF

cat > services/account-service/src/main/java/com/nbwealths/accountservice/controller/AccountController.java <<'EOF'
package com.nbwealths.accountservice.controller;

import com.nbwealths.accountservice.dto.AccountDto;
import com.nbwealths.accountservice.service.AccountService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1/accounts")
public class AccountController {

    private final AccountService accountService;

    public AccountController(AccountService accountService) {
        this.accountService = accountService;
    }

    @PostMapping
    public ResponseEntity<AccountDto> createAccount(@RequestBody AccountDto dto) {
        AccountDto created = accountService.createAccount(dto);
        return ResponseEntity.ok(created);
    }

    @GetMapping("/{id}")
    public ResponseEntity<AccountDto> getAccount(@PathVariable Long id) {
        return accountService.getAccount(id)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }
}
EOF

cat > services/account-service/src/main/java/com/nbwealths/accountservice/dto/AccountDto.java <<'EOF'
package com.nbwealths.accountservice.dto;

public class AccountDto {
    private Long id;
    private String owner;
    private String type;
    private String currency;
    private Double balance;

    public AccountDto() {}

    public AccountDto(Long id, String owner, String type, String currency, Double balance) {
        this.id = id;
        this.owner = owner;
        this.type = type;
        this.currency = currency;
        this.balance = balance;
    }

    // getters and setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getOwner() { return owner; }
    public void setOwner(String owner) { this.owner = owner; }
    public String getType() { return type; }
    public void setType(String type) { this.type = type; }
    public String getCurrency() { return currency; }
    public void setCurrency(String currency) { this.currency = currency; }
    public Double getBalance() { return balance; }
    public void setBalance(Double balance) { this.balance = balance; }
}
EOF

cat > services/account-service/src/main/java/com/nbwealths/accountservice/entity/Account.java <<'EOF'
package com.nbwealths.accountservice.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "accounts")
public class Account {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String owner;
    private String type;
    private String currency;
    private Double balance;

    // getters and setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getOwner() { return owner; }
    public void setOwner(String owner) { this.owner = owner; }
    public String getType() { return type; }
    public void setType(String type) { this.type = type; }
    public String getCurrency() { return currency; }
    public void setCurrency(String currency) { this.currency = currency; }
    public Double getBalance() { return balance; }
    public void setBalance(Double balance) { this.balance = balance; }
}
EOF

cat > services/account-service/src/main/java/com/nbwealths/accountservice/repository/AccountRepository.java <<'EOF'
package com.nbwealths.accountservice.repository;

import com.nbwealths.accountservice.entity.Account;
import org.springframework.data.jpa.repository.JpaRepository;

public interface AccountRepository extends JpaRepository<Account, Long> {
}
EOF

cat > services/account-service/src/main/java/com/nbwealths/accountservice/service/AccountService.java <<'EOF'
package com.nbwealths.accountservice.service;

import com.nbwealths.accountservice.dto.AccountDto;
import com.nbwealths.accountservice.entity.Account;
import com.nbwealths.accountservice.repository.AccountRepository;
import org.springframework.stereotype.Service;

import java.util.Optional;

@Service
public class AccountService {

    private final AccountRepository accountRepository;

    public AccountService(AccountRepository accountRepository) {
        this.accountRepository = accountRepository;
    }

    public AccountDto createAccount(AccountDto dto) {
        Account a = new Account();
        a.setOwner(dto.getOwner());
        a.setType(dto.getType());
        a.setCurrency(dto.getCurrency());
        a.setBalance(dto.getBalance() == null ? 0.0 : dto.getBalance());
        Account saved = accountRepository.save(a);
        return toDto(saved);
    }

    public Optional<AccountDto> getAccount(Long id) {
        return accountRepository.findById(id).map(this::toDto);
    }

    private AccountDto toDto(Account a) {
        return new AccountDto(a.getId(), a.getOwner(), a.getType(), a.getCurrency(), a.getBalance());
    }
}
EOF

cat > services/account-service/src/main/resources/application-docker.yml <<'EOF'
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-account:5432/${POSTGRES_ACCOUNT_DB}
    username: ${POSTGRES_ACCOUNT_USER}
    password: ${POSTGRES_ACCOUNT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

keycloak:
  auth-server-url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_ACCOUNT_CLIENT_ID}

kafka:
  bootstrap-servers: kafka:9092
EOF

cat > services/account-service/src/main/resources/application-local.yml <<'EOF'
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_ACCOUNT_DB}
    username: ${POSTGRES_ACCOUNT_USER}
    password: ${POSTGRES_ACCOUNT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

keycloak:
  auth-server-url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_ACCOUNT_CLIENT_ID}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
EOF

cat > services/account-service/src/main/resources/db/migration/V1__init.sql <<'EOF'
-- Flyway baseline for account service

CREATE TABLE IF NOT EXISTS accounts (
  id SERIAL PRIMARY KEY,
  owner VARCHAR(255) NOT NULL,
  type VARCHAR(50),
  currency VARCHAR(10),
  balance NUMERIC(19,4) DEFAULT 0
);
EOF

cat > services/account-service/src/test/java/com/nbwealths/accountservice/AccountServiceIntegrationTest.java <<'EOF'
package com.nbwealths.accountservice;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@SpringBootTest
@Testcontainers
public class AccountServiceIntegrationTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:14")
            .withDatabaseName("testdb")
            .withUsername("test")
            .withPassword("test");

    @Test
    void contextLoads() {
        // simple context load test; real tests will wire a datasource with postgres.getJdbcUrl()
    }
}
EOF

cat > services/account-service/Dockerfile <<'EOF'
FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8081

ENTRYPOINT ["java","-jar","/app/app.jar"]
EOF

# portfolio service
cat > services/portfolio-service/pom.xml <<'EOF'
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.nbwealths</groupId>
        <artifactId>nbwealths-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>portfolio-service</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
EOF

cat > services/portfolio-service/src/main/java/com/nbwealths/portfoliosvc/PortfolioServiceApplication.java <<'EOF'
package com.nbwealths.portfoliosvc;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class PortfolioServiceApplication {
    public static void main(String[] args) {
        SpringApplication.run(PortfolioServiceApplication.class, args);
    }
}
EOF

cat > services/portfolio-service/src/main/java/com/nbwealths/portfoliosvc/controller/PortfolioController.java <<'EOF'
package com.nbwealths.portfoliosvc.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/v1/portfolios")
public class PortfolioController {

    @GetMapping
    public ResponseEntity<String> ping() {
        return ResponseEntity.ok("portfolio-service up");
    }
}
EOF

cat > services/portfolio-service/src/main/resources/application-docker.yml <<'EOF'
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres-portfolio:5432/${POSTGRES_PORTFOLIO_DB}
    username: ${POSTGRES_PORTFOLIO_USER}
    password: ${POSTGRES_PORTFOLIO_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

kafka:
  bootstrap-servers: kafka:9092
EOF

cat > services/portfolio-service/src/main/resources/application-local.yml <<'EOF'
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_PORTFOLIO_DB}
    username: ${POSTGRES_PORTFOLIO_USER}
    password: ${POSTGRES_PORTFOLIO_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
EOF

cat > services/portfolio-service/src/main/resources/db/migration/V1__init.sql <<'EOF'
-- Flyway baseline for portfolio service

CREATE TABLE IF NOT EXISTS portfolios (
  id SERIAL PRIMARY KEY,
  owner VARCHAR(255) NOT NULL,
  name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS positions (
  id SERIAL PRIMARY KEY,
  portfolio_id INT REFERENCES portfolios(id),
  symbol VARCHAR(32),
  quantity NUMERIC(19,4),
  avg_price NUMERIC(19,6)
);
EOF

cat > services/portfolio-service/Dockerfile <<'EOF'
FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8082

ENTRYPOINT ["java","-jar","/app/app.jar"]
EOF

# admin service
cat > services/admin-service/pom.xml <<'EOF'
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.nbwealths</groupId>
        <artifactId>nbwealths-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>admin-service</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
EOF

cat > services/admin-service/src/main/java/com/nbwealths/adminsvc/AdminServiceApplication.java <<'EOF'
package com.nbwealths.adminsvc;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class AdminServiceApplication {
    public static void main(String[] args) {
        SpringApplication.run(AdminServiceApplication.class, args);
    }
}
EOF

cat > services/admin-service/src/main/java/com/nbwealths/adminsvc/controller/AdminController.java <<'EOF'
package com.nbwealths.adminsvc.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/v1/admin")
public class AdminController {

    @GetMapping("/ping")
    public ResponseEntity<String> ping() {
        return ResponseEntity.ok("admin-service up");
    }
}
EOF

cat > services/admin-service/src/main/resources/application-docker.yml <<'EOF'
server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://postgres-admin:5432/${POSTGRES_ADMIN_DB}
    username: ${POSTGRES_ADMIN_USER}
    password: ${POSTGRES_ADMIN_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
EOF

cat > services/admin-service/src/main/resources/application-local.yml <<'EOF'
server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/${POSTGRES_ADMIN_DB}
    username: ${POSTGRES_ADMIN_USER}
    password: ${POSTGRES_ADMIN_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
EOF

cat > services/admin-service/src/main/resources/db/migration/V1__init.sql <<'EOF'
-- Flyway baseline for admin service

CREATE TABLE IF NOT EXISTS roles (
  id SERIAL PRIMARY KEY,
  name VARCHAR(128) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id SERIAL PRIMARY KEY,
  actor VARCHAR(255),
  action VARCHAR(255),
  created_at TIMESTAMP DEFAULT NOW(),
  detail TEXT
);
EOF

cat > services/admin-service/Dockerfile <<'EOF'
FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8083

ENTRYPOINT ["java","-jar","/app/app.jar"]
EOF

# frontend placeholder
cat > frontend/angular-app/package.json <<'EOF'
{
  "name": "nbwealths-frontend",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "ng serve",
    "build": "ng build"
  },
  "dependencies": {
    "@angular/core": "^15.0.0"
  },
  "devDependencies": {}
}
EOF

cat > frontend/angular-app/README.md <<'EOF'
# frontend placeholder

This will be an Angular app located at frontend/angular-app. For now it's a placeholder; we'll scaffold components and Keycloak OIDC integration next.
EOF

echo "Staging all files..."
git add -A

if git status --porcelain | grep -q .; then
  echo "Committing..."
  git commit -m "scaffold: full monorepo scaffold (services, infra, docker-compose, keycloak realm, CI, migrations, Dockerfiles, placeholders)" || true
else
  echo "No changes to commit."
fi

echo "Pushing branch $BRANCH to origin..."
git push --set-upstream origin "$BRANCH"

echo "Done. Branch $BRANCH pushed. Verify on GitHub."