server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_PORTFOLIO_DB}
    username: ${POSTGRES_PORTFOLIO_USER}
    password: ${POSTGRES_PORTFOLIO_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
