server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-account:5432/${POSTGRES_ACCOUNT_DB}
    username: ${POSTGRES_ACCOUNT_USER}
    password: ${POSTGRES_ACCOUNT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

keycloak:
  auth-server-url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_ACCOUNT_CLIENT_ID}

kafka:
  bootstrap-servers: kafka:9092
